########
# PORT #
########
server:
  port: 8282
  # number threads for rest calls
  number-of-threads: 20
  # after this time we remove agents
  disable-agent-millis: 10000 # 10 sec
#############
# SCHEDULER #
#############
scheduler:
  # check for instance if agents are outdated
  update-agent-interval-millis: 5000 # 5 sec
spring:
###########
# PROFILE #
###########
  profiles: local
  application:
    name: happy-solver-server
###########
# MONITOR #
###########
  boot:
    admin:
      client:
        url: http://localhost:8283
        instance:
          preferIp: true
############
# LANGUAGE #
############
  mvc:
    locale: en_US
    locale-resolver: fixed
############
# DATABASE #
############
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/happyserver
    username: happyserver
    password: happyserver
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.PostgreSQL9Dialect
    # show_sql: true
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
#############
# ACTURATOR #
#############
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: full
###########
# LOGGING #
###########
logging:
  level:
    ROOT: INFO
    